### ISSUE TITLE
Upload mappings from file

### ISSUE THREAD

**Issue by hellocatfood** [riban-bw/nanoKONTROL-Config#9]
I have a nanokontrol config file that I want to upload to the device using this software. Here's file file https://drive.google.com/file/d/13RWh1ghB1_RZHBXjxlMrQFll_5I38UPi/view (it was obtained from here https://andreijaycreativecoding.com/VSERPI-hardware-and-images , under MIDI CONTROLLER SCENE SETTINGS)

Can an option be added to this software to do this?

**Comment by riban-bw** [comment]
This looks like a proprietor file format from another program. I don't have that other program nor a mechanism to reverse engineer the file format. I don't think it likely that nanoKONTROL-Config will every support other programs' file formats. It may be possible to add our own file format to allow saving and recalling configuration but that would be subject of a feature request.
